[tool.poetry]
name = "experiments"
version = "0.1.0"
description = ""
authors = ["Amity Aharoni <amittai-shlomo.aharoni@student.uva.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
